<?php

namespace Tests\Feature\Http\Controllers;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\CourseController
 */
class CourseControllerTest extends TestCase
{
    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('get-courses-list'));

        $response->assertOk();
        $response->assertViewIs('courses.list');
        $response->assertViewHas('defaultPeriod');
        $response->assertViewHas('isAllowedToEdit');
        $response->assertViewHas('rhythms');
        $response->assertViewHas('levels');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function search_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('search-courses'));

        $response->assertOk();

        // TODO: perform additional assertions
    }

    // test cases...
}
