<?php

namespace Tests\Feature\Http\Controllers;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\GradeController
 */
class GradeControllerTest extends TestCase
{
    /**
     * @test
     */
    public function add_grade_type_to_course_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post('course/gradetype', [
            // TODO: send request data
        ]);

        $response->assertRedirect(back());

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function destroy_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->delete('grades');

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function edit_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $course = factory(\App\Models\Course::class)->create();

        $response = $this->get('course/{course}/grades');

        $response->assertOk();
        $response->assertViewIs('grades.edit');
        $response->assertViewHas('enrollments');
        $response->assertViewHas('course_grade_types');
        $response->assertViewHas('grades');
        $response->assertViewHas('course');
        $response->assertViewHas('all_grade_types');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function remove_grade_type_from_course_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $course = factory(\App\Models\Course::class)->create();
        $grade = factory(\App\Models\Grade::class)->create();

        $response = $this->delete('course/{course}/gradetype/{gradetype}');

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post('grades', [
            // TODO: send request data
        ]);

        $response->assertOk();

        // TODO: perform additional assertions
    }

    // test cases...
}
