<?php

namespace Tests\Feature\Http\Controllers;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Language
 */
class LanguageTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function back_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('language::back', ['locale' => $locale]));

        $response->assertRedirect(to($session->previousUrl()));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function home_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('language::home', ['locale' => $locale]));

        $response->assertRedirect(to($url));

        // TODO: perform additional assertions
    }

    // test cases...
}
