<?php

namespace Tests\Feature\Http\Controllers;

use Tests\TestCase;

/**
 * @see \App\Http\Controllers\TeacherLeaveController
 */
class TeacherLeaveControllerTest extends TestCase
{
    /**
     * @test
     */
    public function leaves_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('teachersLeaves'));

        $response->assertOk();
        $response->assertViewIs('leaves.index');
        $response->assertViewHas('teachers');

        // TODO: perform additional assertions
    }

    // test cases...
}
