<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreatePreInvoicesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('pre_invoices', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('user_id')->unsigned(); // the client
            $table->integer('user_data_id')->unsigned()->nullable(); // the data to use in the invoice
            //$table->string('products'); // serialized products paid in the invoice.
            $table->integer('enrollment_id')->unsigned()->nullable(); // enrollment id

            // the following is here to keep all the data from the old system.
            //TODO check if this is really needed, otherwise remove it.
            $table->string('client_name')->nullable(); // client name.
            $table->string('client_idnumber')->nullable(); // client passport.
            $table->string('client_address')->nullable(); // client address.
            $table->string('client_email')->nullable(); // client email.
            $table->decimal('total_price', 8, 2)->nullable(); // final invoice price.


            $table->integer('company_id')->default(1); // link to copany details: name, legal number... - todo
            $table->integer('invoice_number')->nullable(); // the final invoice number, generated by the accounting software
            $table->timestamps();
            $table->softDeletes();
        });

        Schema::create('pre_invoice_details', function (Blueprint $table) {
            $table->increments('id');
            $table->integer('quantity')->unsigned(); // quantity
            $table->integer('pre_invoice_id')->unsigned(); // pre_invoice id
            $table->string('product_name');
            $table->decimal('price', 8, 2);
            $table->timestamps();
            $table->softDeletes();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('pre_invoices');
    }
}
