<?php

namespace Tests\Feature\Http\Controllers\Admin;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Admin\ResultCrudController
 */
class ResultCrudControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('result.index'));

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function search_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->post(route('result.search'), [
            // TODO: send request data
        ]);

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function show_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('result.show', ['id' => $id]));

        $response->assertOk();
        $response->assertViewIs('results.show');
        $response->assertViewHas('enrollment');
        $response->assertViewHas('grades');
        $response->assertViewHas('skills');
        $response->assertViewHas('result');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function show_details_row_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $response = $this->get(route('result.showDetailsRow', ['id' => $id]));

        $response->assertOk();
        $response->assertViewIs('results.show');
        $response->assertViewHas('enrollment');
        $response->assertViewHas('grades');
        $response->assertViewHas('skills');
        $response->assertViewHas('result');

        // TODO: perform additional assertions
    }

    // test cases...
}
